'use client';

import React, { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { api } from '@/lib/api';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { PropertyCard, PropertyData } from '@/components/PropertyCard';
import { MapPin, Bed, Home, Phone, Share2, Calendar, ShieldCheck, Check, MessageSquare } from 'lucide-react';

// Dynamically import DetailMap to bypass window undefined errors on SSR
const DetailMap = dynamic(() => import('@/components/DetailMap'), {
  ssr: false,
  loading: () => <div className="w-full h-80 bg-slate-100 dark:bg-slate-900 rounded-2xl flex items-center justify-center text-xs text-muted animate-pulse">Loading Location Map...</div>,
});

// Simple Helper to render basic markdown generated by Gemini
const renderMarkdown = (md: string) => {
  if (!md) return '';
  return md.split('\n').map((line, idx) => {
    // Heading 3
    if (line.startsWith('### ')) {
      return <h3 key={idx} className="text-base font-bold text-foreground mt-4 mb-2">{line.replace('### ', '')}</h3>;
    }
    // Heading 2
    if (line.startsWith('## ')) {
      return <h2 key={idx} className="text-lg font-bold text-foreground mt-5 mb-2.5 border-b border-border pb-1">{line.replace('## ', '')}</h2>;
    }
    // Bold list items
    if (line.startsWith('- ') || line.startsWith('* ')) {
      const cleanLine = line.substring(2);
      return (
        <li key={idx} className="ml-5 list-disc text-sm text-muted mt-1 leading-relaxed">
          {parseBoldText(cleanLine)}
        </li>
      );
    }
    // Standard paragraphs
    return <p key={idx} className="text-sm text-muted mt-2 leading-relaxed">{parseBoldText(line)}</p>;
  });
};

// Sub-helper to parse bold syntax **text** inside lines
const parseBoldText = (text: string) => {
  const parts = text.split(/\*\*(.*?)\*\*/g);
  return parts.map((part, i) => (i % 2 === 1 ? <strong key={i} className="font-bold text-foreground">{part}</strong> : part));
};

export default function PropertyDetailsPage() {
  const { id } = useParams();
  const router = useRouter();

  // Fetch property details + related items
  const { data, isLoading, error } = useQuery({
    queryKey: ['propertyDetail', id],
    queryFn: async () => {
      const res = await api.get(`/api/properties/${id}`);
      return res.data;
    },
    enabled: !!id,
  });

  const property: PropertyData | null = data?.property || null;
  const relatedList: PropertyData[] = data?.related || [];

  // Gallery slider state
  const [activeImage, setActiveImage] = useState('');

  useEffect(() => {
    if (property && property.images && property.images.length > 0) {
      setActiveImage(property.images[0]);
    }
  }, [property]);

  if (isLoading) {
    return (
      <div className="min-h-screen flex flex-col bg-background">
        <Navbar />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-sm font-semibold text-muted animate-pulse">Loading Listing Details...</div>
        </div>
        <Footer />
      </div>
    );
  }

  if (error || !property) {
    return (
      <div className="min-h-screen flex flex-col bg-background">
        <Navbar />
        <div className="flex-1 flex flex-col items-center justify-center p-4">
          <h2 className="text-xl font-bold text-foreground">বিজ্ঞপ্তিটি খুঁজে পাওয়া যায়নি</h2>
          <p className="text-xs text-muted mt-1">প্রোপার্টি আইডিটি ভুল অথবা এটি মুছে ফেলা হয়েছে।</p>
          <Link href="/rentals" className="bg-primary text-white text-xs font-semibold px-4 py-2 rounded-lg mt-4">
            রেন্টাল পেজে যান
          </Link>
        </div>
        <Footer />
      </div>
    );
  }

  // Format currency
  const rentFormatted = new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 0 }).format(property.rentAmount);
  const depositFormatted = new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 0 }).format(property.deposit || 0);

  // Setup WhatsApp Redirect link
  const cleanPhone = property.contactPhone.replace(/[\s-+]/g, '');
  // Format international bangladesh phone code if missing (starts with 01)
  const finalWhatsappPhone = cleanPhone.startsWith('01') ? '88' + cleanPhone : cleanPhone;
  const whatsappMessage = `আসসালামু আলাইকুম, আমি RentWise AI-তে আপনার দেওয়া বিজ্ঞাপন "${property.title}" টি দেখেছি এবং বাসাটি ভাড়া নেওয়ার ব্যাপারে বিস্তারিত জানতে আগ্রহী।`;
  const whatsappUrl = `https://wa.me/${finalWhatsappPhone}?text=${encodeURIComponent(whatsappMessage)}`;

  // Default image check
  const fallbackImage = 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=800&auto=format&fit=crop';
  const images = property.images && property.images.length > 0 ? property.images : [fallbackImage];
  const activeDisplayImg = activeImage || images[0];

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />

      <main className="flex-1 py-10 mx-auto max-w-7xl w-full px-4 sm:px-6 lg:px-8">
        
        {/* Breadcrumb / Top Info */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xs bg-primary/10 text-primary font-bold px-2.5 py-1 rounded-full uppercase tracking-wider">
                {property.category}
              </span>
              {property.isBachelorAllowed && (
                <span className="text-xs bg-secondary/10 text-secondary font-bold px-2.5 py-1 rounded-full uppercase tracking-wider">
                  Bachelor Allowed
                </span>
              )}
            </div>
            <h1 className="text-2xl sm:text-3xl font-black text-foreground">{property.title}</h1>
            <div className="flex items-center text-xs text-muted mt-1 gap-1">
              <MapPin className="h-4 w-4 text-accent shrink-0" />
              <span>{property.address}</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => {
                navigator.clipboard.writeText(window.location.href);
                alert('লিংকটি ক্লিপবোর্ডে কপি করা হয়েছে!');
              }}
              className="p-2 border border-border bg-card hover:bg-slate-50 rounded-xl text-muted hover:text-foreground transition-colors cursor-pointer"
              title="লিংক শেয়ার করুন"
            >
              <Share2 className="h-4.5 w-4.5" />
            </button>
          </div>
        </div>

        {/* Primary Page Layout Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start mb-16">
          
          {/* Left Column (Images, specs, description) */}
          <div className="lg:col-span-8 space-y-8">
            
            {/* Image Slider Gallery */}
            <div className="space-y-3">
              <div className="h-[300px] sm:h-[450px] w-full rounded-2xl overflow-hidden border border-border bg-slate-100 relative">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={activeDisplayImg}
                  alt={property.title}
                  className="w-full h-full object-cover"
                />
              </div>

              {/* Thumbnails row */}
              {images.length > 1 && (
                <div className="flex gap-2 overflow-x-auto pb-1">
                  {images.map((img, idx) => (
                    <button
                      key={idx}
                      onClick={() => setActiveImage(img)}
                      className={`h-16 w-24 rounded-lg overflow-hidden border-2 shrink-0 cursor-pointer transition-all ${
                        activeDisplayImg === img ? 'border-primary' : 'border-border opacity-70'
                      }`}
                    >
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={img} alt="thumbnail" className="w-full h-full object-cover" />
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Core Specs metrics */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-5 bg-card border border-border rounded-2xl">
              <div className="text-center p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-border/40">
                <Bed className="h-5 w-5 text-primary mx-auto mb-1" />
                <span className="block text-[10px] text-muted font-semibold uppercase">Bedrooms</span>
                <span className="text-sm font-bold text-foreground">{property.bedrooms} Rooms</span>
              </div>
              <div className="text-center p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-border/40">
                <Home className="h-5 w-5 text-primary mx-auto mb-1" />
                <span className="block text-[10px] text-muted font-semibold uppercase">Bathrooms</span>
                <span className="text-sm font-bold text-foreground">{property.bathrooms} Baths</span>
              </div>
              <div className="text-center p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-border/40">
                <Calendar className="h-5 w-5 text-primary mx-auto mb-1" />
                <span className="block text-[10px] text-muted font-semibold uppercase">Rent Amount</span>
                <span className="text-sm font-bold text-foreground">{rentFormatted}</span>
              </div>
              <div className="text-center p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-border/40">
                <ShieldCheck className="h-5 w-5 text-primary mx-auto mb-1" />
                <span className="block text-[10px] text-muted font-semibold uppercase">Advance Deposit</span>
                <span className="text-sm font-bold text-foreground">{depositFormatted}</span>
              </div>
            </div>

            {/* Description Card */}
            <div className="bg-card border border-border p-6 sm:p-8 rounded-2xl">
              <h2 className="text-lg font-bold text-foreground pb-2.5 border-b border-border flex items-center gap-2">
                <Home className="h-5 w-5 text-primary" />
                বাসার বিবরণ ও সুযোগ-সুবিধা
              </h2>
              
              <div className="mt-4 space-y-1">
                {renderMarkdown(property.description)}
              </div>
            </div>

            {/* Amenities Grid checklist */}
            <div className="bg-card border border-border p-6 rounded-2xl">
              <h3 className="font-bold text-sm text-foreground mb-4">কমন এমেনিটিজ ও সুবিধাসমূহ</h3>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs sm:text-sm text-muted">
                {['সার্বক্ষণিক নিরাপত্তা প্রহরী', 'সরাসরি গ্যাস কানেকশন', 'জেনারেটর ব্যাকআপ', 'লিফট (Lift) সুবিধা', 'সিসিটিভি ক্যামেরা নিরাপত্তা', 'পর্যাপ্ত আলো-বাতাস'].map((amenity, idx) => (
                  <div key={idx} className="flex items-center gap-2">
                    <Check className="h-4 w-4 text-emerald-600 shrink-0" />
                    <span>{amenity}</span>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* Right Column: Contact CTAs & Location Map Card */}
          <div className="lg:col-span-4 space-y-6">
            
            {/* Contact Panel Card */}
            <div className="bg-card border border-border p-6 rounded-2xl space-y-5">
              <div className="text-center">
                <span className="text-xs text-muted block">মাসিক ভাড়া</span>
                <span className="text-3xl font-black text-primary block mt-1">{rentFormatted}</span>
                {property.deposit > 0 && (
                  <span className="text-xs text-muted mt-1 block">অগ্রিম অগ্রিম জামানত: {depositFormatted}</span>
                )}
              </div>
              
              <hr className="border-border" />

              <div className="space-y-3">
                {/* 1. Phone Call CTA */}
                <a
                  href={`tel:${property.contactPhone}`}
                  className="w-full bg-primary hover:bg-primary-hover text-white text-xs sm:text-sm font-bold py-3.5 rounded-xl transition-colors flex items-center justify-center gap-2 shadow-sm cursor-pointer"
                >
                  <Phone className="h-4.5 w-4.5" />
                  <span>ল্যান্ডলর্ডকে কল দিন ({property.contactPhone})</span>
                </a>

                {/* 2. Direct WhatsApp CTA */}
                <a
                  href={whatsappUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-full bg-secondary hover:bg-secondary-hover text-white text-xs sm:text-sm font-bold py-3.5 rounded-xl transition-colors flex items-center justify-center gap-2 shadow-sm cursor-pointer"
                >
                  <MessageSquare className="h-4.5 w-4.5" />
                  <span>হোয়াটসঅ্যাপ মেসেজ পাঠান</span>
                </a>
              </div>

              <div className="text-center pt-2">
                <span className="text-[10px] text-muted leading-relaxed block max-w-[220px] mx-auto">
                  * বিজ্ঞাপন নিয়ে যেকোনো চুক্তি বা লিজ করার আগে সশরীরে বাসা পরিদর্শন করতে ভুলবেন না।
                </span>
              </div>
            </div>

            {/* Geolocation Map Pin Card */}
            <div className="bg-card border border-border p-5 rounded-2xl space-y-4">
              <h3 className="font-bold text-sm text-foreground flex items-center gap-2">
                <MapPin className="h-4.5 w-4.5 text-accent" />
                বাসার ম্যাপ লোকেশন
              </h3>
              
              {property.location?.coordinates && (
                <DetailMap
                  lat={property.location.coordinates[1]}
                  lng={property.location.coordinates[0]}
                  address={property.address}
                />
              )}
            </div>

          </div>

        </div>

        {/* Related Items Section */}
        {relatedList.length > 0 && (
          <section className="border-t border-border pt-12">
            <h2 className="text-xl sm:text-2xl font-black text-foreground mb-8">এই এলাকার কাছাকাছি প্রোপার্টির অফার</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {relatedList.map((item) => (
                <PropertyCard key={item._id} property={item} />
              ))}
            </div>
          </section>
        )}

      </main>

      <Footer />
    </div>
  );
}
